# Generated by Django 6.0.3 on 2026-03-07 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_add_owner_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
                ('project_details', models.TextField(blank=True)),
                ('project_link', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'project',
                'ordering': ['project_id'],
            },
        ),
    ]
