# Generated by Django 6.0.3 on 2026-03-07 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_project_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='img_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='img_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
