# Generated by Django 6.0.3 on 2026-03-07 02:47

from django.db import migrations


def create_login_users(apps, schema_editor):
    User = apps.get_model('users', 'User')
    users_data = [
        ('arzu', 'arzu', 'arzu@example.com'),
        ('ahad', 'ahad', 'ahad@example.com'),
        ('hasan', 'hasan', 'hasan@example.com'),
    ]
    for username, password, email in users_data:
        user, created = User.objects.get_or_create(
            username=username,
            defaults={'email': email}
        )
        if created:
            user.set_password(password)
            user.save()


def reverse_create_login_users(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User.objects.filter(username__in=['arzu', 'ahad', 'hasan']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_login_log'),
    ]

    operations = [
        migrations.RunPython(create_login_users, reverse_create_login_users),
    ]
