# Generated by Django

from django.contrib.auth.hashers import make_password
from django.db import migrations


def add_user_login(apps, schema_editor):
    User = apps.get_model('users', 'User')
    user, created = User.objects.get_or_create(
        username='user',
        defaults={'email': 'user@example.com'}
    )
    if created:
        user.password = make_password('user')
        user.save()


def reverse_add_user_login(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User.objects.filter(username='user').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_login_users_arzu_ahad_hasan'),
    ]

    operations = [
        migrations.RunPython(add_user_login, reverse_add_user_login),
    ]
