# Generated by Django 4.2.29 on 2026-03-08 05:09

from django.db import migrations, models


def backfill_user_fields(apps, schema_editor):
    User = apps.get_model('users', 'User')
    for u in User.objects.all():
        if u.created_date is None and hasattr(u, 'date_joined') and u.date_joined:
            u.created_date = u.date_joined
        if not u.name and (u.first_name or u.last_name):
            u.name = f'{u.first_name or ""} {u.last_name or ""}'.strip() or u.username
        u.save(update_fields=['created_date', 'name'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_add_login_user_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_date', '-date_joined']},
        ),
        migrations.AddField(
            model_name='user',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.RunPython(backfill_user_fields, noop_reverse),
    ]
