# Generated by Django - set hasan user role to superadmin

from django.db import migrations


def set_hasan_superadmin(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User.objects.filter(username='hasan').update(role='superadmin')


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_add_superadmin_table'),
    ]

    operations = [
        migrations.RunPython(set_hasan_superadmin, noop_reverse),
    ]
