# Generated by Django 4.2.29 on 2026-03-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_add_upload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to='project_images/'),
        ),
    ]
