# Generated by Django 4.2.29 on 2026-03-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_add_project_image_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('blog_title', models.CharField(max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
                ('blog_content', models.TextField(blank=True)),
                ('blog_link', models.URLField(blank=True, max_length=500)),
                ('img_url', models.URLField(blank=True, max_length=500)),
                ('image_file', models.FileField(blank=True, null=True, upload_to='blog_images/')),
            ],
            options={
                'db_table': 'blog',
                'ordering': ['blog_id'],
            },
        ),
    ]
