# Generated by Django 4.2.29 on 2026-03-11 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_add_blog_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='status',
            field=models.CharField(blank=True, choices=[('incoming', 'Incoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='incoming', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('incoming', 'Incoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='incoming', max_length=20),
        ),
    ]
