# Generated by Django 4.2.29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_add_date_to_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingInvoice',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('own_com_name', models.CharField(blank=True, max_length=255)),
                ('own_com_title', models.CharField(blank=True, max_length=255)),
                ('own_com_logo', models.URLField(blank=True, max_length=500)),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('client_id', models.CharField(blank=True, max_length=100)),
                ('client_company', models.CharField(blank=True, max_length=255)),
                ('client_phone', models.CharField(blank=True, max_length=50)),
                ('client_address', models.TextField(blank=True)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('billing_description', models.TextField(blank=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
            options={
                'db_table': 'billing_invoice',
                'ordering': ['-invoice_date', '-invoice_id'],
            },
        ),
    ]
