# Generated by Django 4.2.29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_add_billing_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('com_id', models.AutoField(primary_key=True, serialize=False)),
                ('own_com_name', models.CharField(blank=True, max_length=255)),
                ('own_com_title', models.CharField(blank=True, max_length=255)),
                ('own_com_logo', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'companyinfo',
                'ordering': ['com_id'],
            },
        ),
    ]
