# Generated by Django 4.2.29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_add_companyinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinginvoice',
            name='company_info',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='invoices',
                to='users.CompanyInfo',
            ),
        ),
    ]
