# Generated by Django 4.2.29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_add_company_info_to_billing_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinginvoice',
            name='own_com_logo_file',
            field=models.ImageField(blank=True, null=True, upload_to='invoice_logos/'),
        ),
    ]
