# Generated by Django 4.2.29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_billinginvoice_own_com_logo_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinginvoice',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
